insert into status_type (STATUS_TYPE_ID, DESCRIPTION, PARENT_ID) value (4, 'ALERT', null);
insert into status_type (STATUS_TYPE_ID, DESCRIPTION, PARENT_ID) value (5, 'SIN TRATAMIENTO', 4);
insert into status_type (STATUS_TYPE_ID, DESCRIPTION, PARENT_ID) value (6, 'ASIGNADA', 4);
insert into status_type (STATUS_TYPE_ID, DESCRIPTION, PARENT_ID) value (7, 'CERRADA', 4);
insert into status_type (STATUS_TYPE_ID, DESCRIPTION, PARENT_ID) value (8, 'SOSPECHOSA', 4);

insert into alert_management (CREATED_BY, CREATED_DATE, DIFFERENCE, MONITORING, PERIOD_AMOUNT, PERIOD_ANALYZED, PERIOD_DESCRIPTION, UIF_REPORT, ASSIGNED_USER_ID, CLIENT_ID, UNUSUAL_OPERATION_STATUS_TYPE_ID) value ('system', '2018-2-16', 100050,'',250050, '2018-1-1', 'Enero-18', '2018-1-10',6,21,6);
insert into alert_management (CREATED_BY, CREATED_DATE, DIFFERENCE, MONITORING, PERIOD_AMOUNT, PERIOD_ANALYZED, PERIOD_DESCRIPTION, UIF_REPORT, ASSIGNED_USER_ID, CLIENT_ID, UNUSUAL_OPERATION_STATUS_TYPE_ID) value ('system', '2018-2-16',3000,'',55000, '2018-1-1', 'Enero-18', '2018-1-10',2,23,6);
insert into alert_management (CREATED_BY, CREATED_DATE, DIFFERENCE, MONITORING, PERIOD_AMOUNT, PERIOD_ANALYZED, PERIOD_DESCRIPTION, UIF_REPORT, ASSIGNED_USER_ID, CLIENT_ID, UNUSUAL_OPERATION_STATUS_TYPE_ID) value ('system', '2018-2-16',7000,'',60000, '2018-1-1', 'Enero-18', '2018-1-10',7,24,7);
insert into alert_management (CREATED_BY, CREATED_DATE, DIFFERENCE, MONITORING, PERIOD_AMOUNT, PERIOD_ANALYZED, PERIOD_DESCRIPTION, UIF_REPORT, ASSIGNED_USER_ID, CLIENT_ID, UNUSUAL_OPERATION_STATUS_TYPE_ID) value ('system', '2018-2-16',7000,'',60000, '2018-1-1', 'Enero-18', '2018-1-10',null,27,5);
insert into alert_management (CREATED_BY, CREATED_DATE, DIFFERENCE, MONITORING, PERIOD_AMOUNT, PERIOD_ANALYZED, PERIOD_DESCRIPTION, UIF_REPORT, ASSIGNED_USER_ID, CLIENT_ID, UNUSUAL_OPERATION_STATUS_TYPE_ID) value ('system', '2018-2-16',45000,'',100000, '2018-1-1', 'Enero-18', '2018-1-10',1,25,6);